version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - ransomware-net
    volumes:
      - zookeeper-data:/var/lib/zookeeper  # Persist Zookeeper data

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - ransomware-net
    volumes:
      - kafka-data:/var/lib/kafka  # Persist Kafka data

  flink:
    image: apache/flink:1.16.0-scala_2.12
    container_name: flink
    environment:
      - FLINK_PROPERTIES
    ports:
      - "8081:8081"  # Flink Web UI
    depends_on:
      - kafka
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/jobmanager/overview || exit 1"]
      interval: 30s
      retries: 3
    networks:
      - ransomware-net
    command: ["jobmanager"]  # Run as JobManager by default

  taskmanager:
    image: apache/flink:1.16.0-scala_2.12
    container_name: flink-taskmanager
    environment:
      - FLINK_PROPERTIES
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"  # Kafka connection
    expose:
      - "6121"
      - "6122"
    depends_on:
      - flink
    command: ["taskmanager"]  # Run as TaskManager by default
    networks:
      - ransomware-net

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
     - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USER_BUCKET=${DEFAULT_BUCKET}
      - INFLUXDB_ADMIN_USER=${ADMIN_USERNAME}
      - INFLUXDB_ADMIN_USER_PASSWORD=${ADMIN_PASSWORD}
      - INFLUXDB_ADMIN_USER_TOKEN=${AUTH_TOKEN}
    networks:
      - ransomware-net

  grafana:
    image: grafana/grafana:9.3.0
    container_name: grafana
    ports:
      - "3000:3000"  # Expose Grafana port
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - influxdb
    networks:
      - ransomware-net
    volumes:
      - grafana-data:/var/lib/grafana  # Volume for Grafana data persistence

  producer:
    image: python:3.11-slim
    container_name: producer
    build:
      context: ./producer
    working_dir: /app
    volumes:
      - ./producer:/app
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
    networks:
      - ransomware-net
    command: ["python", "producer.py"]

  flink_consumer:
    build:
      context: ./flink_consumer
    container_name: flink_consumer
    networks:
      - ransomware-net
    depends_on:
      - kafka
      - influxdb
    command: ["python3", "flink_job.py"]

  time_series_analysis:
    image: python:3.11-slim
    container_name: time_series_analysis
    build:
      context: ./analysis
    working_dir: /app
    volumes:
      - ./analysis:/app
    depends_on:
      - influxdb
    networks:
      - ransomware-net
    command: ["python", "time_series_analysis.py"]

networks:
  ransomware-net:
    driver: bridge

volumes:
  kafka-data:       # Persist Kafka data
  zookeeper-data:   # Persist Zookeeper data
  influxdb-data:    # Persist InfluxDB data
  grafana-data:     # Persist Grafana data
