# Use the official Apache Spark image as the base
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy dependency file and install requirements
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy application script
COPY spark_consumer.py /app/

# Set default command to run the Spark application
CMD ["python3", "spark_consumer.py"]
